# Generated by Django 3.1.5 on 2021-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveyance',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
