# Generated by Django 3.1.5 on 2021-05-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_conveyance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveyance',
            name='RemarkAdmin',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
