# Generated by Django 3.1.5 on 2021-05-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_conveyance_remarkadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('Day', models.CharField(max_length=50)),
                ('Occasion', models.CharField(max_length=50)),
            ],
        ),
    ]
