# Generated by Django 3.1.5 on 2021-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Topic', models.CharField(max_length=50)),
                ('Info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Author', models.CharField(max_length=50)),
                ('Info', models.TextField()),
            ],
        ),
    ]
